# metadata
openapi: 3.0.0
info:
  title: Hotel Management Services # API name
  description: A set of services, which are used to manage Hotel Booking Processes. # Optional. Extended information about the API
  version: 1.0.0

# servers (not yet implemented)

# path
paths: # defines individual endpoints (paths) in your API
  /rooms:
    get:
      summary: Returns list of available rooms.
      description: Find available rooms according searching criteria.
      tags:
        - Booking Services
      parameters:
        - name: start_date
          description: Check-in date.
          in: query
          schema:
            type: string
            format: date
        - name: end_date
          description: Check-out date.
          in: query
          schema:
            type: string
            format: date
        - name: guests_number
          description: Total number of guests.
          in: query
          schema:
            type: integer
            minimum: 1
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/findroomRs"
              examples:
                findroomExampleRs:
                  $ref: "#/components/examples/findroomExampleRs"
        400: # Bad Request
          description: Requested data error.
        500: # Internal Server Error
          description: The Booking Service is currently not available.
  /bookings: # endpoint name
    post:
      summary: Create Booking # short service description
      description: This resource used to create booking.
      tags:
        - Booking Services
      requestBody:
        description: Request used to create booking.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createbookingRq"
            examples:
              createbookingExampleRq:
                $ref: "#/components/examples/createbookingExampleRq"
      responses: # required
        201: # Created.
          description: The booking was sucessfully created.
          headers:
            Location:
              description: Contains URL for created resourse.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/createbookingRs"
              examples:
                createbookingExampleRs:
                  $ref: "#/components/examples/createbookingExampleRs"
        404: # Not found
          description: The requested room is no longer available.
        409: # Conflict
          description: The requested room is already booked for the specified dates.
        500: # Internal Server Error
          description: The Booking Service is currently not available.

  /bookings/{booking_id}:
    parameters:
      - name: booking_id
        description: The booking unique identifier.
        in: path
        required: true
        schema:
          type: string
          pattern: "^[a-zA-Z0-9]{15}"
    patch: # TBD
      summary: Cancel booking.
      description: This resource used to cancel existing booking.
      tags:
        - Booking Services
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/cancelbookingRq"
            examples:
              cancelbookingExampleRq:
                $ref: "#/components/examples/cancelbookingExampleRq"
      responses:
        200:
          description: Canceled.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/createbookingRs"
              examples:
                cancelbookingExampleRs:
                  $ref: "#/components/examples/cancelbookingExampleRs"
        404:
          description: The booking with the particular ID wasn't found.
        409:
          description: The booking with the particular was cancelled.
        500:
          description: The Booking Service is currently not available.
    put:
      summary: Update booking details.
      description: Update booking details.
      tags:
        - Booking Services
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createbookingRq"
            examples:
              updatebookingExamplesRq:
                $ref: "#/components/examples/updatebookingExampleRq"
      responses:
        200:
          description: The details were successfully updated.
        404:
          description: The booking with the particular ID is not found.
        409:
          description: The booking with the particular ID has been cancelled.
        500:
          description: The Booking Service is currently not available.
components:
  schemas:
    findroomRs:
      title: findroomRs
      description: Provides the list of available rooms.
      type: object
      properties:
        start_date:
          description: The begining of the date period.
          type: string
          format: date
        end_date:
          description: The end of the date period.
          type: string
          format: date
        rooms:
          description: The list of the rooms.
          type: array
          items:
            type: object
            properties:
              room_id:
                description: The room unique identifier.
                type: integer
              room_number:
                description: The room number.
                type: string
              room_type:
                description: The room type.
                type: string
              description:
                description: The room description.
                type: string
              price:
                description: The room price.
                type: number
              guests_allowed:
                description: The number of guest allowed in the room.
                type: integer
                minimum: 1
            required:
              - room_id
              - room_number
              - room_type
              - description
              - price
              - guests_allowed
      required:
        - start_date
        - end_date
        - rooms
    createbookingRq:
      title: createbookingRq
      description: This schema describes a request structure of the booking creating.
      type: object
      properties:
        guest:
          type: object
          properties:
            first_name:
              description: The guest's first name.
              type: string
              maxLength: 35
            last_name:
              description: The guest's last name.
              type: string
              maxLength: 35
            contact_number:
              description: The guest's contact number.
              type: string
              maxLength: 35
            email:
              description: The guest's email adress.
              type: string
              format: email
          required:
            - first_name
            - last_name
            - contact_number
            - email
        checkin_date:
          description: The check-in date.
          type: string
          format: date
        checkout_date:
          description: The check-out date.
          type: string
          format: date
        hotel_id:
          description: The unique idetifier of the hotel.
          type: integer
        num_rooms:
          description: The number of the booked rooms.
          type: integer
          minimum: 1
        deposit_type:
          description: Indication on if the customer made a deposit to guarantee the booking.
          type: string
          enum:
            - No Deposit
            - Non Refund
            - Refundable
        rooms:
          description: The list of the booked rooms.
          type: array
          items:
            type: object
            properties:
              room_type:
                type: string
                enum:
                  - A
                  - B
                  - C
                  - D
                  - F
                  - E
              adults:
                description: Number of adults.
                type: integer
                minimum: 0
              children:
                description: Number of children.
                type: integer
                minimum: 0
              babies:
                description: Number of babies.
                type: integer
                minimum: 0
              meal:
                description: Specifies a meal type.
                type: string
                enum:
                  - Undefined
                  - SC
                  - BB
                  - HB
                  - FB
              additional_requests:
                description: The guest's additional request about the room.
                type: string
                maxLength: 500
              price:
                description: A room price, including meal.
                type: object
                properties:
                  amount:
                    description: Number of money units, specified in the currency.
                    type: number
                    minimum: 0
                  currency:
                    description: Currency code, according the standard ISO 4217.
                    type: string
                    pattern: "^([A-Z]{3,3})$"
                required:
                  - amount
                  - currency
            required:
              - room_type
              - adults
              - children
              - babies
              - meal
              - price
      required:
        - guest
        - checkin_date
        - checkout_date
        - hotel_id
        - num_rooms
        - deposit_type
        - rooms
    createbookingRs:
      title: createbookingRs
      description: This schema describes a response structure of the booking creating.
      type: object
      properties:
        guest:
          type: object
          properties:
            guest_id:
              description: The guest's unique identifier.
              type: integer
            first_name:
              description: The guest's first name.
              type: string
              maxLength: 35
            last_name:
              description: The guest's last name.
              type: string
              maxLength: 35
            contact_number:
              description: The guest's contact number.
              type: string
              maxLength: 35
            email:
              description: The guest's email adress.
              type: string
              format: email
          required:
            - guest_id
            - first_name
            - last_name
            - contact_number
            - email
        checkin_date:
          description: The check-in date.
          type: string
          format: date
        checkout_date:
          description: The check-out date.
          type: string
          format: date
        hotel_id:
          description: The unique idetifier of the hotel.
          type: integer
        num_rooms:
          description: The number of the booked rooms.
          type: integer
          minimum: 1
        deposit_type:
          description: Indication on if the customer made a deposit to guarantee the booking.
          type: string
          enum:
            - No Deposit
            - Non Refund
            - Refundable
        rooms:
          description: The list of the booked rooms.
          type: array
          items:
            type: object
            properties:
              room_type:
                type: string
                enum:
                  - A
                  - B
                  - C
                  - D
                  - F
                  - E
              adults:
                description: Number of adults.
                type: integer
                minimum: 0
              children:
                description: Number of children.
                type: integer
                minimum: 0
              babies:
                description: Number of babies.
                type: integer
                minimum: 0
              meal:
                description: Specifies a meal type.
                type: string
                enum:
                  - Undefined
                  - SC
                  - BB
                  - HB
                  - FB
              additional_requests:
                description: The guest's additional request about the room.
                type: string
                maxLength: 500
              price:
                description: A room price, including meal.
                type: object
                properties:
                  amount:
                    description: Number of money units, specified in the currency.
                    type: number
                    minimum: 0
                  currency:
                    description: Currency code, according the standard ISO 4217.
                    type: string
                    pattern: "^([A-Z]{3,3})$"
                required:
                  - amount
                  - currency
            required:
              - room_type
              - adults
              - children
              - babies
              - meal
              - price
        status:
          description: Reservation status.
          type: string
          enum:
            - To Be Confirmed
            - Confirmed
            - Canceled
            - Check-out
            - No-Show
      required:
        - guest
        - checkin_date
        - checkout_date
        - hotel_id
        - num_rooms
        - deposit_type
        - rooms
        - status
    cancelbookingRq:
      title: cancelbookingRq
      description: Describes the request for booking cancellation.
      type: object
      properties:
        update_date:
          description: The date and time, when status was updated.
          type: string
          format: datetime
        status:
          description: Booking status.
          type: string
          enum:
            - To Be Confirmed
            - Confirmed
            - Canceled
            - Check-out
            - No-Show
  examples:
    findroomExampleRs:
      summary: A list of three available rooms.
      value:
        start_date: "2022-03-01"
        end_date: "2022-03-05"
        rooms:
          - room_id: "353546456365"
            room_number: "101"
            room_type: Standard
            description: >-
              This room features a queen-sized bed, a flat-screen TV, air conditioning,
              and a private bathroom with a shower and free toiletries.
            price: 100
            guests_allowed: 2
          - room_id: "3535464564565"
            room_number: "102"
            room_type: Deluxe
            description: >-
              This room features a king-sized bed, a seating area, a flat-screen TV, air
              conditioning, and a private bathroom with a shower, a bathtub, and free
              toiletries.
            price: 150
            guests_allowed: 2
          - room_id: "3535445365"
            room_number: "103"
            room_type: Suite
            description: >-
              This room features a separate living room, a king-sized bed, a flat-screen
              TV, air conditioning, and a private bathroom with a shower, a bathtub, and
              free toiletries.
            price: 200
            guests_allowed: 4
    updatebookingExampleRq:
      summary: The request for booking creating.
      value:
        guest:
          first_name: John
          last_name: Doe
          contact_number: "1234567889"
          email: johndoe@example.com
        checkin_date: "2022-01-01"
        checkout_date: "2022-01-05"
        hotel_id: "1235353467"
        num_rooms: 2
        deposit_type: No Deposit
        rooms:
          - room_type: A
            adults: 2
            children: 0
            babies: 0
            meal: BB
            additional_requests: I would like a room with a view.
          - room_type: B
            adults: 2
            children: 0
            babies: 0
            meal: FB
    createbookingExampleRq:
      summary: The request example for creating booking.
      value:
        guest:
          first_name: John
          last_name: Doe
          contact_number: 123-456-7890
          email: johndoe@example.com
        checkin_date: "2022-01-01"
        checkout_date: "2022-01-02"
        hotel_id: 123456789012345
        num_rooms: 2
        deposit_type: Refundable
        rooms:
          - room_type: A
            adults: 2
            children: 1
            babies: 0
            meal: HB
            additional_requests: Non-smoking room
            price:
              amount: 200.0
              currency: USD
          - room_type: B
            adults: 1
            children: 0
            babies: 0
            meal: BB
            additional_requests: ""
            price:
              amount: 150.0
              currency: USD
    createbookingExampleRs:
      summary: The response example for creating booking.
      value:
        guest:
          guest_id: 123456789012345
          first_name: "John"
          last_name: "Doe"
          contact_number: "123-456-7890"
          email: "johndoe@example.com"
        checkin_date: "2022-01-01"
        checkout_date: "2022-01-02"
        hotel_id: 123456789012345
        num_rooms: 2
        deposit_type: "Refundable"
        rooms:
          - room_type: "A"
            adults: 2
            children: 1
            babies: 0
            meal: "HB"
            additional_requests: "Non-smoking room"
            price:
              amount: 200.0
              currency: "USD"
          - room_type: "B"
            adults: 1
            children: 0
            babies: 0
            meal: "BB"
            additional_requests: ""
            price:
              amount: 150.0
              currency: "USD"
        status: "To Be Confirmed"
    cancelbookingExampleRq:
      summary: The request example of booking cancellation.
      value:
        update_date: "2023-03-20T10:45:00"
        status: Canceled
    cancelbookingExampleRs:
      summary: The response example of booking cancellation.
      value:
        guest:
          guest_id: 123456789012345
          first_name: John
          last_name: Doe
          contact_number: 123-456-7890
          email: johndoe@example.com
        checkin_date: "2022-01-01"
        checkout_date: "2022-01-02"
        hotel_id: 123456789012345
        num_rooms: 2
        deposit_type: Refundable
        rooms:
          - room_type: A
            adults: 2
            children: 1
            babies: 0
            meal: HB
            additional_requests: Non-smoking room
            price:
              amount: 200
              currency: USD
          - room_type: B
            adults: 1
            children: 0
            babies: 0
            meal: BB
            additional_requests: ""
            price:
              amount: 150
              currency: USD
        status: Canceled
